/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      left_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      right_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  left_arm_controller:
    ros__parameters:
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      joints:
        - left_fr3_joint1
        - left_fr3_joint2
        - left_fr3_joint3
        - left_fr3_joint4
        - left_fr3_joint5
        - left_fr3_joint6
        - left_fr3_joint7

  right_arm_controller:
    ros__parameters:
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      joints:
        - right_fr3_joint1
        - right_fr3_joint2
        - right_fr3_joint3
        - right_fr3_joint4
        - right_fr3_joint5
        - right_fr3_joint6
        - right_fr3_joint7
